In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace=True)

In [ ]:
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
df.shape

(569, 31)

In [ ]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

train_test_split

In [ ]:
X_train,x_test,Y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,:1],test_size=0.2,random_state=42)

In [ ]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,0.08046,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,0.07398,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,0.06963,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,0.06329,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,0.06960,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,0.08980,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,0.05376,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,0.06544,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550
102,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,0.05677,...,13.340,32.84,84.58,547.8,0.11230,0.08862,0.11450,0.07431,0.2694,0.06878

In [ ]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
204,12.47,18.60,81.09,481.9,0.09965,0.10580,0.08005,0.03821,0.1925,0.06373,...,14.97,24.64,96.05,677.9,0.1426,0.2378,0.2671,0.10150,0.3014,0.08750
70,18.94,21.31,123.60,1130.0,0.09009,0.10290,0.10800,0.07951,0.1582,0.05461,...,24.86,26.58,165.90,1866.0,0.1193,0.2336,0.2687,0.17890,0.2551,0.06589
131,15.46,19.48,101.70,748.9,0.10920,0.12230,0.14660,0.08087,0.1931,0.05796,...,19.26,26.00,124.90,1156.0,0.1546,0.2394,0.3791,0.15140,0.2837,0.08019
431,12.40,17.68,81.47,467.8,0.10540,0.13160,0.07741,0.02799,0.1811,0.07102,...,12.88,22.91,89.61,515.8,0.1450,0.2629,0.2403,0.07370,0.2556,0.09359
540,11.54,14.44,74.65,402.9,0.09984,0.11200,0.06737,0.02594,0.1818,0.06782,...,12.26,19.68,78.78,457.8,0.1345,0.2118,0.1797,0.06918,0.2329,0.08134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,14.64,16.85,94.21,666.0,0.08641,0.06698,0.05192,0.02791,0.1409,0.05355,...,16.46,25.44,106.00,831.0,0.1142,0.2070,0.2437,0.07828,0.2455,0.06596
75,16.07,19.65,104.10,817.7,0.09168,0.08424,0.09769,0.06638,0.1798,0.05391,...,19.77,24.56,128.80,1223.0,0.1500,0.2045,0.2829,0.15200,0.2650,0.06387
249,11.52,14.93,73.87,406.3,0.10130,0.07808,0.04328,0.02929,0.1883,0.06168,...,12.65,21.19,80.88,491.8,0.1389,0.1582,0.1804,0.09608,0.2664,0.07809
238,14.22,27.85,92.55,623.9,0.08223,0.10390,0.11030,0.04408,0.1342,0.06129,...,15.75,40.54,102.50,764.0,0.1081,0.2426,0.3064,0.08219,0.1890,0.07796
265,20.73,31.12,135.70,1419.0,0.09469,0.11430,0.13670,0.08646,0.1769,0.05674,...,32.49,47.16,214.00,3432.0,0.1401,0.2644,0.3442,0.16590,0.2868,0.08218

In [ ]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
y_test = encoder.fit_transform(y_test)

NameError: name 'LabelEncoder' is not defined

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(x_test)
Y_train_tensor = torch.from_numpy(Y_train)
y_test_tensor = torch.from_numpy(y_test)

## Define Neural Network

In [ ]:
class simpleneural():
  def __init__(self,x):
    self.weights = torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.rand(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x):
    return torch.sigmoid(torch.matmul(x,self.weights) + self.bias)

  def loss_fxn(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [ ]:
learning_rate = 0.05
epochs = 20000

### training pipeline

In [ ]:

#create model
model = simpleneural(X_train_tensor)
model.weights
model.bias

#define loop
total_loss= 0
for epoch in range(epochs):
  #forward pass
  y_pred =model.forward(X_train_tensor)
  # print(f'y_pred : {y_pred}')
  # print(f'y_train : {Y_train_tensor}')
   #loss calculations
  loss = model.loss_fxn(y_pred,Y_train_tensor)
  # print(f'loss : {loss}')
  total_loss += loss
  #backward pass
  loss.backward()
  #weights/parameters updates
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  #print loss in each epochs
  print(f'loss at epoch {epoch+1} is {loss.item()}')

Streaming output truncated to the last 5000 lines.
loss at epoch 15001 is 0.6597310266209397
loss at epoch 15002 is 0.6597310252531364
loss at epoch 15003 is 0.6597310238857634
loss at epoch 15004 is 0.65973102251882
loss at epoch 15005 is 0.6597310211523064
loss at epoch 15006 is 0.6597310197862224
loss at epoch 15007 is 0.6597310184205679
loss at epoch 15008 is 0.6597310170553425
loss at epoch 15009 is 0.6597310156905462
loss at epoch 15010 is 0.6597310143261789
loss at epoch 15011 is 0.6597310129622401
loss at epoch 15012 is 0.6597310115987299
loss at epoch 15013 is 0.6597310102356484
loss at epoch 15014 is 0.6597310088729949
loss at epoch 15015 is 0.6597310075107693
loss at epoch 15016 is 0.6597310061489716
loss at epoch 15017 is 0.6597310047876019
loss at epoch 15018 is 0.6597310034266595
loss at epoch 15019 is 0.6597310020661444
loss at epoch 15020 is 0.6597310007060566
loss at epoch 15021 is 0.6597309993463959
loss at epoch 15022 is 0.659730997987162
loss at epoch 15023 is 0.6597309966283548
loss at epoch 15024 is 0.6597309952699739
loss at epoch 15025 is 0.6597309939120196
loss at epoch 15026 is 0.6597309925544915
loss at epoch 15027 is 0.6597309911973892
loss at epoch 15028 is 0.6597309898407128
loss at epoch 15029 is 0.6597309884844622
loss at epoch 15030 is 0.659730987128637
loss at epoch 15031 is 0.6597309857732371
loss at epoch 15032 is 0.6597309844182625
loss at epoch 15033 is 0.6597309830637127
loss at epoch 15034 is 0.6597309817095879
loss at epoch 15035 is 0.6597309803558878
loss at epoch 15036 is 0.6597309790026119
loss at epoch 15037 is 0.6597309776497607
loss at epoch 15038 is 0.6597309762973332
loss at epoch 15039 is 0.6597309749453301
loss at epoch 15040 is 0.6597309735937507
loss at epoch 15041 is 0.6597309722425949
loss at epoch 15042 is 0.6597309708918625
loss at epoch 15043 is 0.6597309695415535
loss at epoch 15044 is 0.6597309681916677
loss at epoch 15045 is 0.6597309668422047
loss at epoch 15046 is 0.6597309654931646
loss at epoch 15047 is 0.6597309641445471
loss at epoch 15048 is 0.6597309627963521
loss at epoch 15049 is 0.6597309614485796
loss at epoch 15050 is 0.6597309601012289
loss at epoch 15051 is 0.6597309587543003
loss at epoch 15052 is 0.6597309574077936
loss at epoch 15053 is 0.6597309560617085
loss at epoch 15054 is 0.6597309547160447
loss at epoch 15055 is 0.6597309533708025
loss at epoch 15056 is 0.6597309520259812
loss at epoch 15057 is 0.659730950681581
loss at epoch 15058 is 0.6597309493376015
loss at epoch 15059 is 0.6597309479940426
loss at epoch 15060 is 0.6597309466509044
loss at epoch 15061 is 0.6597309453081862
loss at epoch 15062 is 0.6597309439658884
loss at epoch 15063 is 0.6597309426240103
loss at epoch 15064 is 0.6597309412825522
loss at epoch 15065 is 0.6597309399415137
loss at epoch 15066 is 0.6597309386008945
loss at epoch 15067 is 0.6597309372606948
loss at epoch 15068 is 0.6597309359209141
loss at epoch 15069 is 0.6597309345815525
loss at epoch 15070 is 0.6597309332426096
loss at epoch 15071 is 0.6597309319040852
loss at epoch 15072 is 0.6597309305659795
loss at epoch 15073 is 0.659730929228292
loss at epoch 15074 is 0.6597309278910228
loss at epoch 15075 is 0.6597309265541714
loss at epoch 15076 is 0.6597309252177378
loss at epoch 15077 is 0.659730923881722
loss at epoch 15078 is 0.6597309225461235
loss at epoch 15079 is 0.6597309212109425
loss at epoch 15080 is 0.6597309198761784
loss at epoch 15081 is 0.6597309185418313
loss at epoch 15082 is 0.6597309172079011
loss at epoch 15083 is 0.6597309158743876
loss at epoch 15084 is 0.6597309145412906
loss at epoch 15085 is 0.6597309132086099
loss at epoch 15086 is 0.6597309118763452
loss at epoch 15087 is 0.6597309105444966
loss at epoch 15088 is 0.6597309092130638
loss at epoch 15089 is 0.6597309078820467
loss at epoch 15090 is 0.6597309065514452
loss at epoch 15091 is 0.6597309052212588
loss at epoch 15092 is 0.6597309038914876
loss at epoch 15093 is 0.6597309025621315
loss at epoch 15094 is 0.65973090123319
loss at epoch 15095 is 0.6597308999046636
loss at epoch 15096 is 0.6597308985765515
loss at epoch 15097 is 0.6597308972488535
loss at epoch 15098 is 0.65973089592157
loss at epoch 15099 is 0.6597308945947004
loss at epoch 15100 is 0.6597308932682446
loss at epoch 15101 is 0.6597308919422027
loss at epoch 15102 is 0.6597308906165741
loss at epoch 15103 is 0.6597308892913589
loss at epoch 15104 is 0.6597308879665569
loss at epoch 15105 is 0.659730886642168
loss at epoch 15106 is 0.6597308853181918
loss at epoch 15107 is 0.6597308839946286
loss at epoch 15108 is 0.6597308826714776
loss at epoch 15109 is 0.6597308813487393
loss at epoch 15110 is 0.659730880026413
loss at epoch 15111 is 0.6597308787044986
loss at epoch 15112 is 0.6597308773829965
loss at epoch 15113 is 0.6597308760619058
loss at epoch 15114 is 0.6597308747412268
loss at epoch 15115 is 0.6597308734209593
loss at epoch 15116 is 0.6597308721011029
loss at epoch 15117 is 0.6597308707816575
loss at epoch 15118 is 0.659730869462623
loss at epoch 15119 is 0.6597308681439995
loss at epoch 15120 is 0.6597308668257864
loss at epoch 15121 is 0.6597308655079838
loss at epoch 15122 is 0.6597308641905912
loss at epoch 15123 is 0.659730862873609
loss at epoch 15124 is 0.6597308615570368
loss at epoch 15125 is 0.6597308602408741
loss at epoch 15126 is 0.6597308589251213
loss at epoch 15127 is 0.6597308576097777
loss at epoch 15128 is 0.6597308562948433
loss at epoch 15129 is 0.6597308549803182
loss at epoch 15130 is 0.6597308536662021
loss at epoch 15131 is 0.6597308523524947
loss at epoch 15132 is 0.659730851039196
loss at epoch 15133 is 0.6597308497263058
loss at epoch 15134 is 0.6597308484138238
loss at epoch 15135 is 0.65973084710175
loss at epoch 15136 is 0.6597308457900843
loss at epoch 15137 is 0.6597308444788265
loss at epoch 15138 is 0.6597308431679761
loss at epoch 15139 is 0.6597308418575333
loss at epoch 15140 is 0.6597308405474978
loss at epoch 15141 is 0.6597308392378697
loss at epoch 15142 is 0.6597308379286484
loss at epoch 15143 is 0.659730836619834
loss at epoch 15144 is 0.6597308353114265
loss at epoch 15145 is 0.6597308340034254
loss at epoch 15146 is 0.6597308326958304
loss at epoch 15147 is 0.6597308313886421
loss at epoch 15148 is 0.6597308300818596
loss at epoch 15149 is 0.6597308287754831
loss at epoch 15150 is 0.6597308274695122
loss at epoch 15151 is 0.659730826163947
loss at epoch 15152 is 0.6597308248587872
loss at epoch 15153 is 0.6597308235540326
loss at epoch 15154 is 0.659730822249683
loss at epoch 15155 is 0.6597308209457386
loss at epoch 15156 is 0.659730819642199
loss at epoch 15157 is 0.6597308183390637
loss at epoch 15158 is 0.6597308170363331
loss at epoch 15159 is 0.6597308157340066
loss at epoch 15160 is 0.6597308144320844
loss at epoch 15161 is 0.6597308131305661
loss at epoch 15162 is 0.6597308118294516
loss at epoch 15163 is 0.6597308105287407
loss at epoch 15164 is 0.6597308092284335
loss at epoch 15165 is 0.6597308079285296
loss at epoch 15166 is 0.6597308066290287
loss at epoch 15167 is 0.6597308053299311
loss at epoch 15168 is 0.6597308040312361
loss at epoch 15169 is 0.6597308027329439
loss at epoch 15170 is 0.6597308014350542
loss at epoch 15171 is 0.6597308001375669
loss at epoch 15172 is 0.6597307988404819
loss at epoch 15173 is 0.6597307975437989
loss at epoch 15174 is 0.6597307962475177
loss at epoch 15175 is 0.6597307949516384
loss at epoch 15176 is 0.6597307936561605
loss at epoch 15177 is 0.6597307923610842
loss at epoch 15178 is 0.6597307910664092
loss at epoch 15179 is 0.6597307897721352
loss at epoch 15180 is 0.6597307884782623
loss at epoch 15181 is 0.6597307871847901
loss at epoch 15182 is 0.6597307858917185
loss at epoch 15183 is 0.6597307845990473
loss at epoch 15184 is 0.6597307833067766
loss at epoch 15185 is 0.659730782014906
loss at epoch 15186 is 0.6597307807234354
loss at epoch 15187 is 0.6597307794323647
loss at epoch 15188 is 0.6597307781416936
loss at epoch 15189 is 0.659730776851422
loss at epoch 15190 is 0.6597307755615498
loss at epoch 15191 is 0.6597307742720768
loss at epoch 15192 is 0.659730772983003
loss at epoch 15193 is 0.6597307716943278
loss at epoch 15194 is 0.6597307704060514
loss at epoch 15195 is 0.6597307691181739
loss at epoch 15196 is 0.6597307678306945
loss at epoch 15197 is 0.6597307665436136
loss at epoch 15198 is 0.6597307652569308
loss at epoch 15199 is 0.6597307639706459
loss at epoch 15200 is 0.6597307626847588
loss at epoch 15201 is 0.6597307613992692
loss at epoch 15202 is 0.6597307601141771
loss at epoch 15203 is 0.6597307588294824
loss at epoch 15204 is 0.6597307575451848
loss at epoch 15205 is 0.6597307562612844
loss at epoch 15206 is 0.6597307549777808
loss at epoch 15207 is 0.6597307536946738
loss at epoch 15208 is 0.6597307524119633
loss at epoch 15209 is 0.6597307511296493
loss at epoch 15210 is 0.6597307498477314
loss at epoch 15211 is 0.6597307485662098
loss at epoch 15212 is 0.6597307472850837
loss at epoch 15213 is 0.6597307460043538
loss at epoch 15214 is 0.6597307447240192
loss at epoch 15215 is 0.6597307434440803
loss at epoch 15216 is 0.6597307421645366
loss at epoch 15217 is 0.659730740885388
loss at epoch 15218 is 0.6597307396066343
loss at epoch 15219 is 0.6597307383282754
loss at epoch 15220 is 0.6597307370503115
loss at epoch 15221 is 0.6597307357727418
loss at epoch 15222 is 0.6597307344955664
loss at epoch 15223 is 0.6597307332187853
loss at epoch 15224 is 0.6597307319423985
loss at epoch 15225 is 0.6597307306664053
loss at epoch 15226 is 0.6597307293908059
loss at epoch 15227 is 0.6597307281156001
loss at epoch 15228 is 0.6597307268407875
loss at epoch 15229 is 0.6597307255663686
loss at epoch 15230 is 0.6597307242923424
loss at epoch 15231 is 0.6597307230187093
loss at epoch 15232 is 0.6597307217454691
loss at epoch 15233 is 0.6597307204726215
loss at epoch 15234 is 0.6597307192001662
loss at epoch 15235 is 0.6597307179281034
loss at epoch 15236 is 0.659730716656433
loss at epoch 15237 is 0.6597307153851544
loss at epoch 15238 is 0.6597307141142676
loss at epoch 15239 is 0.6597307128437726
loss at epoch 15240 is 0.6597307115736692
loss at epoch 15241 is 0.659730710303957
loss at epoch 15242 is 0.6597307090346363
loss at epoch 15243 is 0.6597307077657066
loss at epoch 15244 is 0.6597307064971679
loss at epoch 15245 is 0.6597307052290198
loss at epoch 15246 is 0.6597307039612625
loss at epoch 15247 is 0.6597307026938959
loss at epoch 15248 is 0.6597307014269191
loss at epoch 15249 is 0.659730700160333
loss at epoch 15250 is 0.6597306988941366
loss at epoch 15251 is 0.6597306976283303
loss at epoch 15252 is 0.6597306963629136
loss at epoch 15253 is 0.6597306950978863
loss at epoch 15254 is 0.6597306938332486
loss at epoch 15255 is 0.6597306925690001
loss at epoch 15256 is 0.6597306913051406
loss at epoch 15257 is 0.6597306900416701
loss at epoch 15258 is 0.6597306887785884
loss at epoch 15259 is 0.6597306875158954
loss at epoch 15260 is 0.6597306862535909
loss at epoch 15261 is 0.6597306849916746
loss at epoch 15262 is 0.6597306837301468
loss at epoch 15263 is 0.6597306824690067
loss at epoch 15264 is 0.6597306812082544
loss at epoch 15265 is 0.6597306799478899
loss at epoch 15266 is 0.6597306786879134
loss at epoch 15267 is 0.6597306774283237
loss at epoch 15268 is 0.6597306761691215
loss at epoch 15269 is 0.6597306749103065
loss at epoch 15270 is 0.6597306736518783
loss at epoch 15271 is 0.6597306723938371
loss at epoch 15272 is 0.6597306711361824
loss at epoch 15273 is 0.6597306698789143
loss at epoch 15274 is 0.6597306686220323
loss at epoch 15275 is 0.6597306673655369
loss at epoch 15276 is 0.6597306661094272
loss at epoch 15277 is 0.6597306648537036
loss at epoch 15278 is 0.6597306635983655
loss at epoch 15279 is 0.6597306623434132
loss at epoch 15280 is 0.6597306610888463
loss at epoch 15281 is 0.6597306598346646
loss at epoch 15282 is 0.6597306585808681
loss at epoch 15283 is 0.6597306573274565
loss at epoch 15284 is 0.6597306560744298
loss at epoch 15285 is 0.6597306548217877
loss at epoch 15286 is 0.6597306535695303
loss at epoch 15287 is 0.6597306523176572
loss at epoch 15288 is 0.6597306510661681
loss at epoch 15289 is 0.6597306498150635
loss at epoch 15290 is 0.6597306485643424
loss at epoch 15291 is 0.6597306473140052
loss at epoch 15292 is 0.6597306460640516
loss at epoch 15293 is 0.6597306448144815
loss at epoch 15294 is 0.6597306435652948
loss at epoch 15295 is 0.6597306423164911
loss at epoch 15296 is 0.6597306410680706
loss at epoch 15297 is 0.6597306398200328
loss at epoch 15298 is 0.6597306385723777
loss at epoch 15299 is 0.6597306373251053
loss at epoch 15300 is 0.6597306360782151
loss at epoch 15301 is 0.6597306348317072
loss at epoch 15302 is 0.6597306335855817
loss at epoch 15303 is 0.6597306323398379
loss at epoch 15304 is 0.6597306310944759
loss at epoch 15305 is 0.6597306298494956
loss at epoch 15306 is 0.6597306286048968
loss at epoch 15307 is 0.6597306273606793
loss at epoch 15308 is 0.6597306261168432
loss at epoch 15309 is 0.6597306248733881
loss at epoch 15310 is 0.6597306236303138
loss at epoch 15311 is 0.6597306223876203
loss at epoch 15312 is 0.6597306211453073
loss at epoch 15313 is 0.659730619903375
loss at epoch 15314 is 0.6597306186618229
loss at epoch 15315 is 0.6597306174206509
loss at epoch 15316 is 0.6597306161798588
loss at epoch 15317 is 0.6597306149394465
loss at epoch 15318 is 0.6597306136994142
loss at epoch 15319 is 0.6597306124597614
loss at epoch 15320 is 0.6597306112204879
loss at epoch 15321 is 0.6597306099815937
loss at epoch 15322 is 0.6597306087430787
loss at epoch 15323 is 0.6597306075049425
loss at epoch 15324 is 0.659730606267185
loss at epoch 15325 is 0.6597306050298064
loss at epoch 15326 is 0.6597306037928065
loss at epoch 15327 is 0.6597306025561845
loss at epoch 15328 is 0.659730601319941
loss at epoch 15329 is 0.6597306000840755
loss at epoch 15330 is 0.6597305988485879
loss at epoch 15331 is 0.6597305976134781
loss at epoch 15332 is 0.6597305963787458
loss at epoch 15333 is 0.6597305951443911
loss at epoch 15334 is 0.6597305939104137
loss at epoch 15335 is 0.6597305926768136
loss at epoch 15336 is 0.6597305914435903
loss at epoch 15337 is 0.6597305902107439
loss at epoch 15338 is 0.6597305889782745
loss at epoch 15339 is 0.6597305877461814
loss at epoch 15340 is 0.6597305865144649
loss at epoch 15341 is 0.6597305852831243
loss at epoch 15342 is 0.6597305840521603
loss at epoch 15343 is 0.659730582821572
loss at epoch 15344 is 0.6597305815913598
loss at epoch 15345 is 0.659730580361523
loss at epoch 15346 is 0.659730579132062
loss at epoch 15347 is 0.6597305779029763
loss at epoch 15348 is 0.6597305766742658
loss at epoch 15349 is 0.6597305754459306
loss at epoch 15350 is 0.6597305742179702
loss at epoch 15351 is 0.6597305729903846
loss at epoch 15352 is 0.6597305717631735
loss at epoch 15353 is 0.6597305705363372
loss at epoch 15354 is 0.6597305693098752
loss at epoch 15355 is 0.6597305680837874
loss at epoch 15356 is 0.6597305668580735
loss at epoch 15357 is 0.6597305656327337
loss at epoch 15358 is 0.6597305644077676
loss at epoch 15359 is 0.6597305631831752
loss at epoch 15360 is 0.6597305619589562
loss at epoch 15361 is 0.6597305607351107
loss at epoch 15362 is 0.6597305595116383
loss at epoch 15363 is 0.659730558288539
loss at epoch 15364 is 0.6597305570658124
loss at epoch 15365 is 0.6597305558434587
loss at epoch 15366 is 0.6597305546214776
loss at epoch 15367 is 0.6597305533998689
loss at epoch 15368 is 0.6597305521786324
loss at epoch 15369 is 0.6597305509577683
loss at epoch 15370 is 0.659730549737276
loss at epoch 15371 is 0.6597305485171558
loss at epoch 15372 is 0.6597305472974072
loss at epoch 15373 is 0.6597305460780302
loss at epoch 15374 is 0.6597305448590246
loss at epoch 15375 is 0.6597305436403904
loss at epoch 15376 is 0.6597305424221271
loss at epoch 15377 is 0.6597305412042349
loss at epoch 15378 is 0.6597305399867137
loss at epoch 15379 is 0.659730538769563
loss at epoch 15380 is 0.6597305375527831
loss at epoch 15381 is 0.6597305363363735
loss at epoch 15382 is 0.659730535120334
loss at epoch 15383 is 0.6597305339046647
loss at epoch 15384 is 0.6597305326893655
loss at epoch 15385 is 0.659730531474436
loss at epoch 15386 is 0.6597305302598763
loss at epoch 15387 is 0.659730529045686
loss at epoch 15388 is 0.6597305278318651
loss at epoch 15389 is 0.6597305266184138
loss at epoch 15390 is 0.6597305254053313
loss at epoch 15391 is 0.6597305241926176
loss at epoch 15392 is 0.6597305229802729
loss at epoch 15393 is 0.659730521768297
loss at epoch 15394 is 0.6597305205566895
loss at epoch 15395 is 0.6597305193454504
loss at epoch 15396 is 0.6597305181345795
loss at epoch 15397 is 0.6597305169240767
loss at epoch 15398 is 0.6597305157139418
loss at epoch 15399 is 0.6597305145041747
loss at epoch 15400 is 0.6597305132947754
loss at epoch 15401 is 0.6597305120857435
loss at epoch 15402 is 0.6597305108770789
loss at epoch 15403 is 0.6597305096687818
loss at epoch 15404 is 0.6597305084608515
loss at epoch 15405 is 0.6597305072532882
loss at epoch 15406 is 0.6597305060460917
loss at epoch 15407 is 0.6597305048392619
loss at epoch 15408 is 0.6597305036327986
loss at epoch 15409 is 0.6597305024267015
loss at epoch 15410 is 0.6597305012209708
loss at epoch 15411 is 0.6597305000156062
loss at epoch 15412 is 0.6597304988106073
loss at epoch 15413 is 0.6597304976059745
loss at epoch 15414 is 0.6597304964017071
loss at epoch 15415 is 0.6597304951978054
loss at epoch 15416 is 0.6597304939942689
loss at epoch 15417 is 0.6597304927910975
loss at epoch 15418 is 0.6597304915882913
loss at epoch 15419 is 0.6597304903858501
loss at epoch 15420 is 0.6597304891837735
loss at epoch 15421 is 0.6597304879820618
loss at epoch 15422 is 0.6597304867807144
loss at epoch 15423 is 0.6597304855797314
loss at epoch 15424 is 0.6597304843791126
loss at epoch 15425 is 0.6597304831788579
loss at epoch 15426 is 0.6597304819789669
loss at epoch 15427 is 0.6597304807794397
loss at epoch 15428 is 0.6597304795802766
loss at epoch 15429 is 0.6597304783814768
loss at epoch 15430 is 0.6597304771830401
loss at epoch 15431 is 0.6597304759849668
loss at epoch 15432 is 0.6597304747872565
loss at epoch 15433 is 0.6597304735899091
loss at epoch 15434 is 0.6597304723929246
loss at epoch 15435 is 0.6597304711963027
loss at epoch 15436 is 0.6597304700000431
loss at epoch 15437 is 0.6597304688041461
loss at epoch 15438 is 0.6597304676086113
loss at epoch 15439 is 0.6597304664134385
loss at epoch 15440 is 0.6597304652186275
loss at epoch 15441 is 0.6597304640241786
loss at epoch 15442 is 0.6597304628300911
loss at epoch 15443 is 0.6597304616363652
loss at epoch 15444 is 0.6597304604430005
loss at epoch 15445 is 0.6597304592499973
loss at epoch 15446 is 0.659730458057355
loss at epoch 15447 is 0.6597304568650736
loss at epoch 15448 is 0.659730455673153
loss at epoch 15449 is 0.6597304544815931
loss at epoch 15450 is 0.6597304532903939
loss at epoch 15451 is 0.6597304520995548
loss at epoch 15452 is 0.6597304509090759
loss at epoch 15453 is 0.6597304497189572
loss at epoch 15454 is 0.6597304485291985
loss at epoch 15455 is 0.6597304473397996
loss at epoch 15456 is 0.6597304461507604
loss at epoch 15457 is 0.6597304449620806
loss at epoch 15458 is 0.6597304437737603
loss at epoch 15459 is 0.6597304425857993
loss at epoch 15460 is 0.659730441398197
loss at epoch 15461 is 0.6597304402109541
loss at epoch 15462 is 0.6597304390240698
loss at epoch 15463 is 0.6597304378375443
loss at epoch 15464 is 0.6597304366513771
loss at epoch 15465 is 0.6597304354655686
loss at epoch 15466 is 0.659730434280118
loss at epoch 15467 is 0.659730433095026
loss at epoch 15468 is 0.6597304319102917
loss at epoch 15469 is 0.6597304307259151
loss at epoch 15470 is 0.6597304295418965
loss at epoch 15471 is 0.6597304283582353
loss at epoch 15472 is 0.6597304271749315
loss at epoch 15473 is 0.6597304259919852
loss at epoch 15474 is 0.6597304248093955
loss at epoch 15475 is 0.6597304236271633
loss at epoch 15476 is 0.6597304224452878

## Model evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred_class = (y_pred > 0.6).float()
  accuracy = (y_pred_class == y_test_tensor).float().mean()
  print(f'accuracy : {accuracy}')

accuracy : 0.5280086398124695